apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: vaultflow-pipeline
build:
  artifacts:
    - image: vaultflow-api
      context: ./app
      docker:
        dockerfile: Dockerfile
  local:
    push: false 

manifests:
  hooks:
    before:
      - host:
          command: ["sh", "-c", "kubectl create secret tls vaultflow-tls-secret --cert=vaultflow.crt --key=vaultflow.key --namespace=vaultflow-team-a --dry-run=client -o yaml | kubectl apply -f -"]
  
  helm:
    releases:
      - name: vaultflow-api-team-a
        chartPath: ./charts/vaultflow-api
        namespace: vaultflow-team-a
        setValueTemplates:
          image.repository: "{{.IMAGE_REPO}}"
          image.tag: "{{.IMAGE_TAG}}"
          image.pullPolicy: "IfNotPresent"

deploy:
  helm: {}

# ── 🔒 LOCKED PORT FORWARDING ────────────────────────────────────────
portForward:
  - resourceType: service
    resourceName: ingress-nginx-controller
    namespace: ingress-nginx
    port: 443
    localPort: 8443 # Anchors your proxy to 8443 forever