apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vaultflow-api.fullname" . }}-config-history
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vaultflow-api.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size | default "1Gi" }}
  storageClassName: {{ .Values.storage.className | default "standard" }}