apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vaultflow-api.fullname" . }}-config-history
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vaultflow-api.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}